### ISSUE TITLE
bug(supabase-integration): Invalid argument(s): Field primaryKey on Customer is not serialized by Supabase

### ISSUE THREAD

**Issue by devj3ns** [GetDutchie/brick#424]
Since the adapter issues are fixed, I could run my app to further test the new Supabase integration.

Unfortunately, the following exception was thrown:

```
E/flutter ( 5671): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Field primaryKey on Customer is not serialized by Supabase
E/flutter ( 5671): #0      QuerySupabaseTransformer.expandCondition 
```

<details>
<summary>Full Stack trace</summary>

```
(package:brick_supabase/src/query_supabase_transformer.dart:121:7)
E/flutter ( 5671): #1      QuerySupabaseTransformer.select.<anonymous closure> (package:brick_supabase/src/query_supabase_transformer.dart:44:30)
E/flutter ( 5671): #2      ListBase.fold (dart:collection/list.dart:202:22)
E/flutter ( 5671): #3      QuerySupabaseTransformer.select (package:brick_supabase/src/query_supabase_transformer.dart:43:33)
E/flutter ( 5671): #4      SupabaseProvider.get (package:brick_supabase/src/supabase_provider.dart:70:38)
E/flutter ( 5671): #5      OfflineFirstRepository.hydrate (package:brick_offline_first/src/offline_first_repository.dart:451:53)
E/flutter ( 5671): #6      OfflineFirstRepository.get (package:brick_offline_first/src/offline_first_repository.dart:209:22)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #7      OfflineFirstRepository.getAssociation (package:brick_offline_first/src/offline_first_repository.dart:229:21)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #8      _$ProjectFromSqlite (package:tragwerk_app/brick/adapters/project_adapter.g.dart:63:18)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #9      ProjectAdapter.fromSqlite (package:tragwerk_app/brick/adapters/project_adapter.g.dart:311:7)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #10     Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #11     SqliteProvider.rawGet (package:brick_sqlite/src/sqlite_provider.dart:224:12)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #12     SqliteProvider.get (package:brick_sqlite/src/sqlite_provider.dart:130:12)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #13     OfflineFirstRepository.hydrate.<anonymous closure> (package:brick_offline_first/src/offline_first_repository.dart:462:17)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #14     OfflineFirstRepository.hydrate (package:brick_offline_first/src/offline_first_repository.dart:460:14)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #15     OfflineFirstRepository.get (package:brick_offline_first/src/offline_first_repository.dart:209:16)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #16     OfflineFirstRepository.getBatched.getFrom (package:brick_offline_first/src/offline_first_repository.dart:269:23)
E/flutter ( 5671): <asynchronous suspension>
E/flutter ( 5671): #17     OfflineFirstRepository.getBatched (package:brick_offline_first/src/offline_first_repository.dart:284:12)
E/flutter ( 5671): <asynchronous suspension>
```

</details> 

(Originally the error ends with "...not serialized by SQLite" as seen [here](https://github.com/GetDutchie/brick/blob/188ea28e39fdec4b586efaf48f52581973efb139/packages/brick_supabase/lib/src/query_supabase_transformer.dart#L118), I guess this is a typo and should be "...not serialized by Supabase".)

It gets thrown when I batch query the Projects, which have an associated customer. 

This is the code inside the `_$ProjectFromSqlite` which includes the where clause with the `primaryKey` field which leads to the error:

```dart
customer: (await repository!.getAssociation<Customer>(
        Query.where('primaryKey', data['customer_Customer_brick_id'] as int, limit1: true),
      ))!.first,
```

**Comment by tshedor** [comment]
Resolving in #424

**Comment by tshedor** [comment]
#426 has been merged to `supabase-integration` and has been published
