### ISSUE TITLE
Offline-first sync issue with deletion from remote side

### ISSUE THREAD

**Issue by Shreemanarjun** [GetDutchie/brick#451]
I am experiencing an issue with the **brick_offline_first_with_supabase** library where deletion of a note from the remote side (Supabase) is not syncing correctly with the device. Specifically, when I delete a note from the device, it deletes locally and then syncs with Supabase as expected. However, when I delete a note directly from Supabase, the device is not updating to reflect the deletion. Instead, it continues to show the last saved notes from the SQLite database.

I understand that the library is designed to work offline-first, but I believe there should be more options or policies for configuring the sync behavior between the remote and device sides. This would allow developers to choose how they want to handle sync conflicts and ensure that the data is updated correctly.

Reproduction Steps:

1. Create a note on the device using the brick_offline_first_with_supabase library.
2. Delete the note from the device. Verify that it is deleted locally and synced with Supabase.
3. Delete the same note directly from Supabase.
4. Observe that the device is not updating to reflect the deletion.

## Listener which listen the specific table and updates the notes 

```dart 
final notesListenerProvider = Provider.autoDispose<void>(
  (ref) {
    final sub = Supabase.instance.client
        .from("notes")
        .stream(primaryKey: ['id']).listen(
      (event) async {
        final notes = await ref
            .watch(myRepositoryPod)
            .get<Note>(policy: OfflineFirstGetPolicy.awaitRemote);
        talker.cleanHistory();
        talker.debug("local notes ${notes.length}");
        //  talker.debug("event table $event");
        //TODO : fix delete sync from remote
      },
    );
    ref.onDispose(
      () {
        sub.cancel();
      },
    );
  },
  name: 'notesListenerProvider',
);
```
## Solution
Need more way of syncing things and compare for deleting the rows that does not exist int he remote.

**Comment by hortigado** [comment]
Hi, can you try use mixins https://getdutchie.github.io/brick/#/offline_first/models?id=mixins 
`destructiveLocalSyncFromRemote` Is the solution for it

**Comment by Shreemanarjun** [comment]
## I am getting this after using the mixin

```dart
class MyRepository extends OfflineFirstWithSupabaseRepository
    with DestructiveLocalSyncFromRemoteMixin {}

```

### Getting Error like this

```dart

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      SupabaseProvider.get (package:brick_supabase/src/supabase_provider.dart:64:55)
supabase_provider.dart:64
#1      DestructiveLocalSyncFromRemoteMixin.destructiveLocalSyncFromRemote (package:brick_offline_first/src/mixins/destructive_local_sync_from_remote_mixin.dart:42:48)
destructive_local_sync_from_remote_mixin.dart:42
#2      notesListenerProvider.<anonymous closure>.<anonymous closure> (package:audionotes/features/splash/controller/listeners/note_listener_pod.dart:15:46)
note_listener_pod.dart:15
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
zone.dart:1594
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
stream_impl.dart:365
#5      _DelayedData.perform (dart:async/stream_impl.dart:541:14)
stream_impl.dart:541
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
stream_impl.dart:646
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
stream_impl.dart:617
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
schedule_microtask.dart:40
#9      _startMicrotaskLoop (dart:async/schedule_m<…>

```

**Comment by Shreemanarjun** [comment]
Somehow got the deletion work by like this but sometime it fails , but it works perfectly for 2 devices syncing same remote notes.

```dart

final notesListenerProvider = Provider.autoDispose<void>(
  (ref) {
    final sub = Supabase.instance.client
        .from("notes")
        .stream(primaryKey: ['id']).listen(
      (remoteMaps) async {
        final repo = ref.watch(myRepositoryPod);
        final localNotes = await repo.get<Note>(
          policy: OfflineFirstGetPolicy.awaitRemote,
        );
        talker.cleanHistory();

        talker.debug("local notes ${remoteMaps.length}");
        talker.debug("event table $remoteMaps");
        final remotenotes = remoteMaps
            .map(
              (e) => Note.fromMap(e),
            )
            .toList();
        final localNotesNotInRemote = localNotes.where((localNote) {
          return !remotenotes
              .any((remoteNote) => remoteNote.id == localNote.id);
        }).toList();

        talker.debug(
            "Local notes not in remote: ${localNotesNotInRemote.length}");
        for (final absentNote in localNotesNotInRemote) {
          await repo.deleteNote(
            note: absentNote,
            policy: OfflineFirstDeletePolicy.optimisticLocal,
          );
        }
      },
    );
    ref.onDispose(
      () {
        sub.cancel();
      },
    );
  },
  name: 'notesListenerProvider',
);



```
## Getting error sometime doing the above code

```dart

E/flutter ( 4145): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)) sql 'DELETE FROM `Note` WHERE _brick_id = ?' args [2]
E/flutter ( 4145): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #1      SqfliteDatabaseMixinExt._txnRawUpdateOrDelete.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:318:22)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:36:16)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:517:14)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #4      SqliteProvider.delete (package:brick_sqlite/src/sqlite_provider.dart:65:12)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #5      OfflineFirstRepository._deleteLocal (package:brick_offline_first/src/offline_first_repository.dart:144:25)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #6      OfflineFirstRepository.delete (package:brick_offline_first/src/offline_first_repository.dart:126:23)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #7      OfflineFirstWithSupabaseRepository.delete (package:brick_offline_first_with_supabase/src/offline_first_with_supabase_repository.dart:74:14)




```

**Comment by Shreemanarjun** [comment]
I will raise a pr . I think this will be acheive total sync support.Thanks for this amazing library.❤️

**Comment by tshedor** [comment]
@Shreemanarjun Thank you. To get the table of a model, you can use `supabaseProvider.modelDictionary.adapterFor[TModel]!.supabaseTableName`.

**Comment by tshedor** [comment]
Hey @Shreemanarjun either tomorrow or this week, Supabase is going to publish a blog about Brick. I've triaged this issue and #448 to #454 . Let's continue the discussion there on adding this feature.

**Comment by jtkeyva** [comment]
I had the same issues based on your simple example in the package. Would be nice if the example supported this so we don't have to figure out how to make it work like it "should".

You mentioned high cost using stream...is that the only way? Like how does firebase handle realtime?
